### PR TITLE
Function time_weight_average gives result with unexpected datapoints.…

### LINKED ISSUE #145: Function time_weight_average gives result with unexpected datapoints.
For example if input timeseries starting point have index ```2018-01-16 08:01:00``` then result should have on first index value ```2018-01-16 08:05:00```.  Now it have ```2018-01-16 08:01:00```. Because of that values in result timeseries is also incorrect.

### PR DESCRIPTION
**Pull request by wenta**
… Fixed #145

### CODE REVIEW

File: src/test/scala/carldata/sf/core/TimeSeriesTest.scala [hunk 1]
```diff
@@ -312,20 +314,39 @@ class TimeSeriesTest extends FlatSpec with Matchers {
...
       """
-        |def main(xs: TimeSeries,  d: Number): TimeSeries = time_weight_average(xs, minutes(d))
+        |def main(xs: TimeSeries): TimeSeries = time_weight_average(xs, minutes(5))
       """.stripMargin
-    val now = LocalDateTime.parse("2015-01-01T00:00:00")
-    val idx = Vector(now, now.plusSeconds(15), now.plusSeconds(30), now.plusSeconds(45), now.plusSeconds(65), now.plusSeconds(80))
-    val idx2 = Vector(now, now.plusMinutes(1))
-    val ts = TimeSeries(idx, Vector(1f, 2f, 3f, 3f, 2f, 6f))
-    val expected = TimeSeries(idx2, Vector(2.25f, 4.75f))
+    val now = LocalDateTime.parse("2014-05-01T08:01:00")
```
Comment (klangner) [inline src/test/scala/carldata/sf/core/TimeSeriesTest.scala]: I would say that it is better to create now as 8:00 instead of 8:01

This will make those tests easier to understand

File: src/main/scala/carldata/sf/core/TimeSeriesModule.scala [hunk 2]
```diff
@@ -141,9 +141,17 @@ class TimeSeriesModule extends Runtime {
   def $time_weight_average(xs: TimeSeries[Float], d: Duration): TimeSeries[Float] = {
     def f(x1: (LocalDateTime, Float), x2: (LocalDateTime, Float), tsh: LocalDateTime) = x1._2
 
-    val xs2 = xs.addMissing(d, f)
+    def addToStart(xs: TimeSeries[Float], x: (LocalDateTime, Float)): TimeSeries[Float] = {
```
Comment (klangner) [inline src/main/scala/carldata/sf/core/TimeSeriesModule.scala]: It is better to name this function addHead(). 
And there are better ways to add head  (first) element then taking double reverse and add as last element
```
x._1 +: xs.index
```

File: src/main/scala/carldata/sf/core/TimeSeriesModule.scala [hunk 3]
```diff
@@ -141,9 +141,17 @@ class TimeSeriesModule extends Runtime {
...
+      val idx = (xs.index.reverse :+ x._1).reverse
+      val vs = (xs.values.reverse :+ x._2).reverse
+      TimeSeries(idx, vs)
+    }
+
+    val xs2 = addToStart(xs, (xs.index.head.withMinute(0).withSecond(0), xs.values.head))
```
Comment (klangner) [inline src/main/scala/carldata/sf/core/TimeSeriesModule.scala]: We need to check that list is not empty or use headOption here

But shouldn't we use 0 here as a value?

Comment (wenta) [reply src/main/scala/carldata/sf/core/TimeSeriesModule.scala]: 0 is ok, index matters here

File: src/test/scala/carldata/sf/core/TimeSeriesTest.scala (hunk 1 above)
Comment (wenta) [reply src/test/scala/carldata/sf/core/TimeSeriesTest.scala]: Example test case data start with this index. If I change it result will be diffrent- unexpected.
